rabbitmq/rabbitmq-jms-client

README.md
src/main/java/com/rabbitmq/jms/admin/RMQConnectionFactory.java
src/main/java/com/rabbitmq/jms/admin/RMQDestination.java
src/main/java/com/rabbitmq/jms/client/Completion.java
src/main/java/com/rabbitmq/jms/client/DeliveryExecutor.java
src/main/java/com/rabbitmq/jms/client/RMQConnection.java
src/main/java/com/rabbitmq/jms/client/RMQMessage.java
src/main/java/com/rabbitmq/jms/client/RMQMessageProducer.java
src/main/java/com/rabbitmq/jms/client/RMQSession.java
src/main/java/com/rabbitmq/jms/client/message/RMQObjectMessage.java
src/main/java/com/rabbitmq/jms/parse/ParseTree.java
src/main/java/com/rabbitmq/jms/util/WhiteListObjectInputStream.java
src/test/java/com/rabbitmq/integration/tests/AbstractITQueue.java
src/test/java/com/rabbitmq/integration/tests/AbstractITTopicSSL.java
src/test/java/com/rabbitmq/integration/tests/ObjectMessageSerializationIT.java
src/test/java/com/rabbitmq/integration/tests/SSLSimpleQueueMessageIT.java
src/test/java/com/rabbitmq/integration/tests/SSLSimpleTopicMessageIT.java
src/test/java/com/rabbitmq/jms/admin/RMQConnectionFactoryTest.java
src/test/java/com/rabbitmq/jms/client/ForeignBytesMessageTest.java
src/test/java/com/rabbitmq/jms/client/message/TestMessages.java
src/test/java/com/rabbitmq/jms/util/TestWhiteListObjectSerialization.java

Limit ObjectMessage deserialization with a package white list
ObjectMessages in JMS can be used to transfer arbitrary Java objects
which are then deserialized before or at the time of
being passed on to message listeners.
This opens message consumers up to a range of attacks
that exploit issues in Java object serialization.
Note: attacker must authenticate with RabbitMQ in order
to carry out the attack.
With this commit we introduce a way to white list packages
that can be deserialized when ObjectMessages are consumed:
* Using a system property, `com.rabbitmq.jms.TrustedPackagesPrefixes` (as a comma separated list, e.g. `java,com.rabbitmq,com.myapp`)
* Using RMQConnectionFactory#setTrustedPackages(List<String>)
* Using RMQConnection#setTrustedPackages(List<String>)
* Using …

Limit ObjectMessage deserialization with a package white list

---

doc-notes/docupdates1.3.2.md
src/main/java/com/rabbitmq/jms/admin/RMQConnectionFactory.java
src/main/java/com/rabbitmq/jms/admin/RMQObjectFactory.java
src/main/java/com/rabbitmq/jms/client/RMQConnection.java
src/main/java/com/rabbitmq/jms/client/RMQSession.java
src/test/java/com/rabbitmq/jms/admin/RMQConnectionFactoryTest.java

Adds onMessageTimeoutMs as a JNDI property,
- ...read by `RMQObjectFactory`, defaults to 2000ms
- ...propagated to `RMQConnectionFactory`
- ...propagated to `RMQConnection`
- ...propagated to `RMQSession`
- updated test `RMQConnectionFactoryTest`
- updated documentation `docupdates1.3.2.md`
Integration tests (`mvn clean verify`) still work.
Implements #5

Provide a way to configure onMessageTimeoutMs

---

pom.xml
src/main/java/com/rabbitmq/jms/admin/RMQConnectionFactory.java
src/main/java/com/rabbitmq/jms/client/ConnectionParams.java
src/main/java/com/rabbitmq/jms/client/RMQConnection.java
src/test/java/com/rabbitmq/integration/tests/RabbitMqBasicQosIT.java

Add channel QoS setting

---

pom.xml
src/main/java/com/rabbitmq/jms/admin/RMQConnectionFactory.java
src/main/scripts/query_test_tls_certs_dir.groovy
src/main/scripts/remove_old_test_keystores.groovy
src/test/java/com/rabbitmq/integration/tests/AbstractITTopicSSL.java
src/test/java/com/rabbitmq/integration/tests/RabbitAPIConnectionFactory.java
src/test/java/com/rabbitmq/integration/tests/SSLSimpleQueueMessageIT.java
src/test/java/com/rabbitmq/integration/tests/SSLSimpleTopicMessageIT.java
src/test/java/com/rabbitmq/integration/tests/SslContextIT.java
src/test/resources/rabbit@localhost.config

Fixes #12: Don't override set `SSLContext`
Fixes #14: Allow using default `SSLContext`

Fix and improve SSLContext usage

---

src/main/java/com/rabbitmq/jms/client/RMQMessage.java

With cef06dd, some RMQMessage instances could be
normalised as though it wasn't necessary (the security
issue would happen only on consumption, and normalisation
happens only on publishing). The re-creation of those
RMQMessage instances would make the JMS compliance
test suite fail.
The current commit also enforces trusted package verification
for every received RMQObjectMessage.

Make compliance test suite pass again

---

doc-notes/docupdates1.1.0.md
doc-notes/docupdates1.3.2.md
src/main/java/com/rabbitmq/jms/admin/RMQObjectFactory.java
src/test/java/com/rabbitmq/jms/admin/RMQConnectionFactoryTest.java
src/test/java/com/rabbitmq/jms/admin/RMQObjectFactoryTest.java

Fixes #21 issue.
Allows the user to create client objects on Wildfly via Naming subsystem configuration.
See Wildfly  [JNDI Reference - Naming Subsystem Configuration](https://docs.jboss.org/author/display/WFLY10/JNDI+Reference#JNDIReference-NamingSubsystemConfiguration).
All the properties documented for Tomcat and Spring in [RabbitMQ JMS client](https://www.rabbitmq.com/jms-client.html) documentation are available. 
They have to be configured within environment element of Wildfly object-factory binding configuration.
Note that a new property called _className_ has to be provided, it describes the type of object to create, among the following possible values:
* javax.jms.ConnectionFactory
* javax.jms.QueueConnectionFactory
* javax.jms.TopicConnectionFactory
* javax.jms.Topic
* …

Let RMQObjectFactory handle properties from a hash table

---

src/main/java/com/rabbitmq/jms/admin/RMQConnectionFactory.java
src/main/java/com/rabbitmq/jms/client/ConnectionParams.java
src/main/java/com/rabbitmq/jms/client/RMQConnection.java
src/main/java/com/rabbitmq/jms/client/RMQMessage.java
src/main/java/com/rabbitmq/jms/client/RMQMessageProducer.java
src/main/java/com/rabbitmq/jms/client/RMQSession.java
src/main/java/com/rabbitmq/jms/client/SessionParams.java
src/test/java/com/rabbitmq/jms/client/RMQMessageProducerTest.java

Priority, delivery mode, and expiration aren't taken into
account on sending when set in the JMS message. This is compliant with
the specifiation though. This commit provide a flag in
RMQConnectionFactory to make the RMQMessageProducer use the
message properties if set. This is non-compliant with the specification
but more natural. The existing and spec-compliant behavior is still
the default.
Fixes #26

Take message properties into account on sending

---

src/main/java/com/rabbitmq/jms/admin/RMQConnectionFactory.java
src/main/java/com/rabbitmq/jms/client/ConnectionParams.java
src/main/java/com/rabbitmq/jms/client/DeliveryExecutor.java
src/main/java/com/rabbitmq/jms/client/MessageListenerConsumer.java
src/main/java/com/rabbitmq/jms/client/RMQConnection.java
src/main/java/com/rabbitmq/jms/client/RMQMessageConsumer.java
src/main/java/com/rabbitmq/jms/client/RMQMessageListenerExecutionJMSException.java
src/main/java/com/rabbitmq/jms/client/RMQSession.java
src/main/java/com/rabbitmq/jms/client/SessionParams.java
src/test/java/com/rabbitmq/integration/tests/RequeueMessageOnListenerExceptionIT.java

Requeuing a message after a client RuntimeException complies to
the JMS specification. Nevertheless, the default behavior is
still the same: the message is "lost" (as it has been AMQP-acknowledged
before the delivery to the client) if the client fails to process
it (which makes more sense to us).
The option is RMQConnectionFactory#requeueOnMessageListenerException
and is false by default.
Fixes #23

Add option to requeue message on client runtime exception

---

pom.xml
src/main/java/com/rabbitmq/jms/admin/RMQConnectionFactory.java
src/main/java/com/rabbitmq/jms/client/AmqpPropertiesCustomiser.java
src/main/java/com/rabbitmq/jms/client/ConnectionParams.java
src/main/java/com/rabbitmq/jms/client/RMQConnection.java
src/main/java/com/rabbitmq/jms/client/RMQMessageProducer.java
src/main/java/com/rabbitmq/jms/client/RMQSession.java
src/main/java/com/rabbitmq/jms/client/SessionParams.java
src/test/java/com/rabbitmq/integration/tests/AbstractAmqpITQueue.java
src/test/java/com/rabbitmq/integration/tests/AmqpPropertiesCustomiserIT.java

This allows to customise (e.g. specify a content-type header) outbound
AMQP messages.
Fixes #42

Add AmqpPropertiesCustomiser interface

---

src/main/java/com/rabbitmq/jms/admin/RMQConnectionFactory.java
src/test/java/com/rabbitmq/jms/admin/RMQConnectionFactoryTest.java

For advanced customization (TLS, metrics, threading, etc), just before
the AMQP connection is created.
Fixes #57

Add post-processor for AMQP connection factory

---

src/main/java/com/rabbitmq/jms/admin/RMQConnectionFactory.java
src/main/java/com/rabbitmq/jms/client/ConnectionParams.java
src/main/java/com/rabbitmq/jms/client/RMQConnection.java
src/main/java/com/rabbitmq/jms/client/RMQMessageProducer.java
src/main/java/com/rabbitmq/jms/client/RMQSession.java
src/main/java/com/rabbitmq/jms/client/SendingContext.java
src/main/java/com/rabbitmq/jms/client/SendingContextConsumer.java
src/main/java/com/rabbitmq/jms/client/SessionParams.java
src/test/java/com/rabbitmq/integration/tests/RpcIT.java

This allows changing/checking the destination and the message before
sending. This can be used to avoid creating a destination by calling
setDeclared(true) on it (useful for RPC on temporary queues).
Fixes #47

Add callback before sending message

---

src/main/java/com/rabbitmq/jms/client/MessageListenerConsumer.java
src/main/java/com/rabbitmq/jms/client/RMQMessage.java
src/main/java/com/rabbitmq/jms/client/RMQMessageConsumer.java
src/main/java/com/rabbitmq/jms/client/RMQMessageProducer.java
src/test/java/com/rabbitmq/integration/tests/RpcWithAmqpDirectReplyIT.java

This commit provides support for RabbitMQ direct reply-to when
performing RPC operations. The client just needs to set up the
JMSReplyTo header with a RMQDestination named "amq.rabbitmq.reply-to".
This provides better performance than using a temporary queue, but it
comes with 2 limitations:
* the reply-to destination is an JMS "AMQP" destination, so only
ByteMessages and TextMessages are supported.
* the client needs to create a MessageConsumer and register a
MessageListener to get the response, as direct reply-to doesn't work
with basic.get.
Fixes #48

Handle request-reply with RabbitMQ direct reply-to

---

src/main/java/com/rabbitmq/jms/client/RMQMessage.java
src/test/java/com/rabbitmq/integration/tests/RpcIT.java
src/test/java/com/rabbitmq/integration/tests/RpcWithAmqpDirectReplyIT.java
src/test/java/com/rabbitmq/integration/tests/SendingContextConsumerIT.java

This commit instructs to not declare a reply-to RMQDestination for
consumed messages. This avoids trying to create a second time a
temporary reply-to destination (reply-to destinations are supposed to be
created by a RPC client before sending the request).
This happens to also fix #47.
Fixes #69

Do not declare reply-to destination for consumed messages

---

src/main/java/com/rabbitmq/jms/admin/RMQConnectionFactory.java

This resolves the problem described in #74 by re-ordering the creation of the ConnectionFactory by setting the SSL Context first.

Adjusted order to avoid invalid warning about TrustEverythingTrustManager

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md
LICENSE-MPL-RabbitMQ
LICENSES.txt
doc-notes/docupdates1.1.0.md
doc-notes/docupdates1.3.2.md
src/main/java/com/rabbitmq/jms/admin/RMQConnectionFactory.java
src/main/java/com/rabbitmq/jms/admin/RMQObjectFactory.java
src/main/java/com/rabbitmq/jms/client/RMQMessage.java
src/main/java/com/rabbitmq/jms/util/UriCodec.java
src/test/java/com/rabbitmq/jms/client/message/TestMessages.java

This commit updates URLs to prefer the https protocol. Redirects are not followed to avoid accidentally expanding intentionally shortened URLs (i.e. if using a URL shortener).
These URLs were switched to an https URL with a 2xx status. While the status was successful, your review is still recommended.
* http://docs.oracle.com/javase/7/docs/technotes/guides/security/SunProviders.html with 1 occurrences migrated to:  
https://docs.oracle.com/javase/7/docs/technotes/guides/security/SunProviders.html ([https](https://docs.oracle.com/javase/7/docs/technotes/guides/security/SunProviders.html) result 200).
* http://en.wikipedia.org/wiki/Floating_point with 1 occurrences migrated to:  
https://en.wikipedia.org/wiki/Floating_point ([https](https://en.wikipedia.org/wiki/Floating_point) result 200). …

URL Cleanup

---

src/main/java/com/rabbitmq/jms/client/RMQMessage.java
src/test/java/com/rabbitmq/integration/tests/TtlIT.java

This would break only for AMQP messages converted in to JMS messages.
Fixes #112

Set JMSExpiration to 0 when AMQP expiration is null

---

pom.xml
src/main/java/com/rabbitmq/jms/admin/RMQConnectionFactory.java
src/main/java/com/rabbitmq/jms/client/ConfirmListener.java
src/main/java/com/rabbitmq/jms/client/ConnectionParams.java
src/main/java/com/rabbitmq/jms/client/PublisherConfirmContext.java
src/main/java/com/rabbitmq/jms/client/PublisherConfirmsUtils.java
src/main/java/com/rabbitmq/jms/client/PublishingListener.java
src/main/java/com/rabbitmq/jms/client/RMQConnection.java
src/main/java/com/rabbitmq/jms/client/RMQMessageProducer.java
src/main/java/com/rabbitmq/jms/client/RMQSession.java
src/main/java/com/rabbitmq/jms/client/SessionParams.java
src/test/java/com/rabbitmq/integration/tests/PublisherConfirmsIT.java
src/test/java/com/rabbitmq/jms/client/PublisherConfirmsUtilsTest.java
src/test/java/com/rabbitmq/jms/client/RMQMessageProducerTest.java

Add an optional callback to the RMQConnectionFactory to be notified
of confirmed/nack-ed published messages. Setting this callback will
enable publisher confirms globally (for all the children objects created
by the RMQConnectionFactory instance).
Publisher confirms use a publishing sequence number to correlate
messages. As there is no such concept in JMS, the JMS client takes care
of mapping sequence numbers with original messages.
The confirm callback has one method with one context parameter. This
allows adding more information about published messages later (e.g. the
session or producer instance), without breaking changes. The context
consists now of the original message and a flag for confirmed or nacked.
Fixes #115

Add support for publisher confirms

---

src/main/java/com/rabbitmq/jms/client/RMQSession.java

This gives the user the option to set the options that will be used when declaring a queue in the declareRMQQueue method.
With Rabbit 3.8.0-rc.1 I noticed that when creating classic queues via the management console an argument of "x-queue-type" set to "classic" is created, I assume this is to differentiate between classic and quorum queues. However this prevents channel.queueDeclare calls from working correctly unless an option is provided. This change would also let people use lazy queues and queues with other types of arguments set.
This change would help my team out quite a bit with what we are trying to do, if I can revise this pull request to better fit your standards please let me know. Thanks!

Externalized options used when declaring queue in RMQSession.declareRMQQueue

---

src/main/java/com/rabbitmq/jms/admin/RMQObjectFactory.java
src/test/java/com/rabbitmq/jms/admin/RMQObjectFactoryTest.java

Since channelsQos property is already managed in RMQConnectionFactory, I would like to add some support for applications that use JNDI to connect to a RabbitMQ broker and need to define a prefetch count for performance reasons.

Add channelsQos property to JNDI Factory

---

src/main/java/com/rabbitmq/jms/client/RMQMessage.java
src/test/java/com/rabbitmq/integration/tests/SimpleAmqpQueueMessageIT.java

The property is not supposed to be null in JMS, but it can in AMQP
0.9.1, so JMS messages consumed from AMQP resources can have a null
value. This commit mitigates the issue by returning a timestamp set to 0
in this case, just like the JMS 1.1 specification suggests it when
MessageProducer#setDisableMessageTimestamp(true) is called.
Fixes #126

Return 0 JMS timestamp if property is null

---

src/main/java/com/rabbitmq/jms/admin/RMQConnectionFactory.java
src/main/java/com/rabbitmq/jms/admin/RMQDestination.java
src/main/java/com/rabbitmq/jms/admin/RMQObjectFactory.java
src/test/java/com/rabbitmq/jms/admin/RMQConnectionFactoryTest.java
src/test/java/com/rabbitmq/jms/admin/RMQDestinationTest.java
src/test/java/com/rabbitmq/jms/admin/RMQObjectFactoryTest.java

RMQConnectionFactory#getReference and RMQDestination#getReference now
include enough information to re-create similar instances. All the
properties supported in RMQObjectFactory are now included in
RMQConnectionFactory#getReference.
Fixes #128

Make RMQConnectionFactory and RMQDestination compatible with RMQObjectFactory

---

src/main/java/com/rabbitmq/jms/admin/RMQConnectionFactory.java
src/main/java/com/rabbitmq/jms/admin/RMQDestination.java
src/main/java/com/rabbitmq/jms/admin/RMQObjectFactory.java
src/test/java/com/rabbitmq/jms/admin/RMQConnectionFactoryTest.java
src/test/java/com/rabbitmq/jms/admin/RMQDestinationTest.java
src/test/java/com/rabbitmq/jms/admin/RMQObjectFactoryTest.java

The exchange/routing key/queue properties were all marked as non-nullable, whereas
they can be null. The RMQDestination constructor takes care of checking
the arguments.
Fixes #129

Fix AMQP resource creation in RMQObjectFactory

---

src/main/java/com/rabbitmq/jms/client/RMQMessage.java
src/main/java/com/rabbitmq/jms/client/message/RMQStreamMessage.java
src/test/java/com/rabbitmq/integration/tests/StreamMessageSerializationIT.java

StreamMessage now uses the same "white list" mechanism as
ObjectMessage to avoid some arbitrary code execution on deserialization.
Even though StreamMessage is supposed to handle only primitive types,
it is still to possible to send a message that contains an arbitrary
serializable instance. The consuming application application may
then execute code from this class on deserialization.
The fix consists in using the list of trusted packages that can be
set at the connection factory level.
Fixes #135

Use trusted packages in StreamMessage

---

src/main/java/com/rabbitmq/jms/admin/RMQConnectionFactory.java
src/main/java/com/rabbitmq/jms/admin/RMQObjectFactory.java
src/main/java/com/rabbitmq/jms/client/ConnectionParams.java
src/main/java/com/rabbitmq/jms/client/RMQConnection.java
src/main/java/com/rabbitmq/jms/client/RMQMessage.java
src/main/java/com/rabbitmq/jms/client/RMQMessageProducer.java
src/main/java/com/rabbitmq/jms/client/RMQSession.java
src/main/java/com/rabbitmq/jms/client/SessionParams.java
src/test/java/com/rabbitmq/integration/tests/JmsTypeHeaderAutomaticallySetIT.java
src/test/java/com/rabbitmq/jms/admin/RMQObjectFactoryTest.java

When this option is enabled, the JMSType AMQP header is
set to TextMessage automatically for JMS TextMessages published
to AMQP resources. This way those messages are directly converted
to TextMessages for JMS consumers (instead of BytesMessages).
This avoids changing application code for some use cases: consumers
do not have to do some painful conversion to read the text body from
BytesMessages, they get TextMessages directly. And publishers
do not have to worry about setting the header depending on the
type of destination ("pure" JMS or AMQP).
The property is also settable from JNDI, which allows changing the
types of destinations without changing application code.
The option is disabled by default, so backward compatibility is preserved.

Add autoJmsTypeHeaderForTextMessages property

---

.github/workflows/test-linux.yml
.gitignore
bin/start_rabbitmq.sh
src/main/java/com/rabbitmq/jms/client/DelayedMessageService.java
src/main/java/com/rabbitmq/jms/client/RMQConnection.java
src/main/java/com/rabbitmq/jms/client/RMQMessage.java
src/main/java/com/rabbitmq/jms/client/RMQMessageProducer.java
src/main/java/com/rabbitmq/jms/client/RMQSession.java
src/main/java/com/rabbitmq/jms/client/SessionParams.java
src/test/java/com/rabbitmq/TestUtils.java
src/test/java/com/rabbitmq/integration/tests/DelayedAMQPQueueMessageIT.java
src/test/java/com/rabbitmq/integration/tests/DelayedMessageIT.java
src/test/java/com/rabbitmq/integration/tests/DelayedQueueMessageIT.java
src/test/java/com/rabbitmq/integration/tests/DelayedTopicMessageIT.java
src/test/java/com/rabbitmq/integration/tests/SSLHostnameVerificationIT.java
src/test/java/com/rabbitmq/integration/tests/SSLSimpleQueueMessageIT.java
src/test/java/com/rabbitmq/integration/tests/SSLSimpleTopicMessageIT.java
src/test/java/com/rabbitmq/integration/tests/SslContextIT.java
src/test/java/com/rabbitmq/jms/client/DelayedMessageServiceTest.java
src/test/java/com/rabbitmq/jms/client/RMQMessageProducerTest.java
src/test/java/com/rabbitmq/jms/client/RMQMessageTest.java
src/test/java/com/rabbitmq/jms/client/RMQSessionTest.java
src/test/java/com/rabbitmq/jms/util/Shell.java

This PR implements [JMS_Spec-44](https://jakarta.ee/specifications/messaging/3.1/jakarta-messaging-spec-3.1.html#delivery-delay-jms_spec-44) which permits to delay the delivery of a message after a delay or after certain time. 
The implementation depends on the [delayed message exchange](https://github.com/rabbitmq/rabbitmq-delayed-message-exchange) plugin. If the plugin is not enabled, it fails to send any delayed message. 
This is what happens when you send a delayed message to a destination exchange `X`:
1. Declare `x-delayed-jms-message` exchange of type `x-delayed-message` with the args `x-delayed-type : headers`. This means that the delayed exchange is of type **header**. The JMS client caches the declaration at the JMS Connection level.
2. Bind exchange `X` to exchange …

Support Delayed messages 

---

src/main/java/com/rabbitmq/jms/client/RMQMessage.java
src/main/java/com/rabbitmq/jms/client/RMQMessageProducer.java
src/test/java/com/rabbitmq/jms/client/RMQMessageProducerTest.java
src/test/java/com/rabbitmq/jms/client/RMQMessageTest.java

Reason for update - we have a system that uses IBMMQ via JMS and are converting some operations to use RabbitMQ, rather than IBMMQ. To be able to maintain backwards compatibility and remain technology agnostic, we're using the Rabbit-JMS-Client. rather than than the native rabbitmq client.
This update is a bug fix for allowing the rabbitmq-jms-client to correctly respond to handle the following use cases:
- Replying correctly to a message containing a direct reply to queue by ensuring the rabbit correlation id is set (as well as the JMS Correllation id).
- Forwarding on a message containing a direct reply to queue to a further consumer where a future consumer will reply to the initial client.
- Handling a reply to queue that's not a "direct reply to" or a forwarded
"direct reply to" …

Handle forwarded Direct Reply To and non-Direct Reply To Q's

---

src/main/java/com/rabbitmq/jms/client/RMQMessage.java
src/test/java/com/rabbitmq/jms/client/RMQMessageTest.java

This PR fixes #325 by checking first if the given headers of the RMQMessage is `null`.
Also added a test to verify.

Fix: NPE if a received message is marked as "Redelivered" but no header is given

---

src/main/java/com/rabbitmq/jms/admin/RMQConnectionFactory.java
src/main/java/com/rabbitmq/jms/admin/RMQObjectFactory.java
src/main/java/com/rabbitmq/jms/client/AuthenticationMechanism.java
src/test/java/com/rabbitmq/jms/admin/RMQConnectionFactoryTest.java

Adds feature described in #326 
Instead of exposing `setSaslConfig(SaslConfig)` directly, `AuthenticationMechanism` was introduced in order to keep the `Serializable` and `Referenceable` contracts of `RMQConnectionFactory`.

Add authenticationMechanism property to RMQConnectionFactory

---

src/main/java/com/rabbitmq/jms/admin/RMQConnectionFactory.java
src/test/java/com/rabbitmq/jms/admin/RMQConnectionFactoryTest.java

Follow-up of the discussion [Make it easier to detect blocked connections #1415 ](https://github.com/rabbitmq/rabbitmq-java-client/discussions/1415) in [rabbitmq-java-client](https://github.com/rabbitmq/rabbitmq-java-client) this PR adds a customizer callback for `com.rabbitmq.client.Connection`(s) akin to the customizer callback for `com.rabbitmq.client.ConnectionFactory`

Add customizer callback for AMQP connections

---

src/main/java/com/rabbitmq/jms/client/message/RMQStreamMessage.java
src/test/java/com/rabbitmq/jms/client/message/TestMessages.java

The buffer may not be read entirely, especially if it is larger than the block size.

Fully read input stream for stream message
